### PR TITLE
Updated Packages

### PR DESCRIPTION
**Pull request by Yelinz**

### CODE REVIEW

**Comment by czosel** [comment]
Found something outdated in the Makefile: `@python app/manage.py syncdb --noinput`

**Comment by JohnL17** [comment]
This merge request is not merged because there is a not answered question.
Could you answer the question about the resetting of the django migrations please?

**Comment by Yelinz** [comment]
By runnning ```python app/manage.py migrate --fake-inital``` you can apply the new migration with the existing data.

**Comment by czosel** [comment]
Right, and why were the old migrations removed in the first place?

**Comment by Yelinz** [comment]
South is Deprecated/Redundant after Django 1.6. They added Django Migrations in 1.7 which does the same thing.

**Pull request merged**
